- id: NodeRed_WD
  alias: NodeRed Watchdog
  trigger:
  - platform: state
    entity_id: sensor.node_red
    from: OK
    to: unknown
  action:
  - service: hassio.addon_restart
    data:
      addon: core_mosquitto
  - service: hassio.addon_restart
    data:
      addon: 7ad98f9c_zigbee2mqtt
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
- id: '1553840795096'
  alias: Restart NodeRed
  trigger:
  - entity_id: sensor.node_red
    from: OK
    platform: state
    to: unknown
  condition: []
  action:
  - data:
      addon: core_mosquitto
    service: hassio.addon_restart
- id: '1582497126970'
  alias: Turn Up brightness
  description: ''
  trigger:
  - device_id: ad8736bc801648b4ba81ef1eb0de1b1a
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_press
  condition: []
  action:
  - device_id: 62390f5e347049308cddec4ecbb130b3
    domain: light
    entity_id: light.hue_livingroom_spot_4
    type: brightness_increase
