- id: '1582569212742'
  alias: Brightness Livingroom Up
  description: ''
  trigger:
  - device_id: a76275d0f39d4025bd32aaefe371086c
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_rotated
  condition: []
  action:
    service: light.turn_on
    data:
      brightness_step_pct: 10
      entity_id:
      - light.lightgroup_livingroom
- id: '1582569212743'
  alias: Brightness Livingroom Down
  description: ''
  trigger:
  - device_id: a76275d0f39d4025bd32aaefe371086c
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_rotated
  condition: []
  action:
    service: light.turn_on
    data:
      brightness_step_pct: -10
      entity_id:
      - light.lightgroup_livingroom