- id: NodeRed_WD
  alias: NodeRed Watchdog
  trigger:
  - platform: state
    entity_id: sensor.node_red
    from: OK
    to: unknown
  action:
  - service: hassio.addon_restart
    data:
      addon: core_mosquitto
  - service: hassio.addon_restart
    data:
      addon: 7ad98f9c_zigbee2mqtt
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
- id: '1553840795096'
  alias: Restart NodeRed
  trigger:
  - entity_id: sensor.node_red
    from: OK
    platform: state
    to: unknown
  condition: []
  action:
  - data:
      addon: core_mosquitto
    service: hassio.addon_restart
- id: '1582569212742'
  alias: Brightness Livingroom Up
  description: ''
  trigger:
  - device_id: a76275d0f39d4025bd32aaefe371086c
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_rotated
  condition: []
  action:
    service: light.turn_on
    data:
      brightness_step_pct: 10
      entity_id:
      - light.lightgroup_livingroom
- id: '1582569212743'
  alias: Brightness Livingroom Down
  description: ''
  trigger:
  - device_id: a76275d0f39d4025bd32aaefe371086c
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_rotated
  condition: []
  action:
    service: light.turn_on
    data:
      brightness_step_pct: -10
      entity_id:
      - light.lightgroup_livingroom