- id: NodeRed_WD
  alias: NodeRed Watchdog
  trigger:
  - platform: state 
    entity_id: sensor.node_red
    from: OK
    to: unknown
  action:
  - service: hassio.addon_restart
    data:
      addon: core_mosquitto
  - service: hassio.addon_restart
    data:
      addon: 7ad98f9c_zigbee2mqtt
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
